### ISSUE TITLE
0 kilobytes for AES encryption

### ISSUE THREAD

**Issue by ghost** [RCStep/CSSG#3]
I've got a default 3.9. it couldn't generate beacon. its 0 kilobytes. the encryption wouldn't work. XOR IS OK , But its not the case for aes.

**Comment by RCStep** [comment]
Did you install the pycryptodome dependency?

Also, the aggressor script (line 190) will use by default the "python" command for the OS you're using (windows/linux), so make sure pycryptodome is installed for the version used by "python"

You could also edit the aggressor script to use a different specific version of python if you wish.
